### ISSUE TITLE
Blender 2.93 Support

### ISSUE THREAD

**Issue by VeissieV** [3DSinghVFX/align_nodes#3] opened 2021-03-22 19:08 UTC
Doesn't seem to work in 2.93. I have it installed but the pie menus don't come up when using the default shortcuts or custom shortcuts.

Looking forward to getting this working. It looks very helpful :)

Thanks

**Comment by 3DSinghVFX** [comment] 2022-04-28 05:23
It seems to work on my side. Can you please try the fresh installation of the addon?

**Comment by VeissieV** [comment] 2022-04-28 06:22
Seems to be working fine now in 3.1.2
Thanks

**Comment by 3DSinghVFX** [comment] 2022-04-28 08:23
The issue is resolved, so I'm closing it.

**Closed as completed by 3DSinghVFX** 2022-04-28 08:23 UTC
